version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: testcontainer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Testing@1122
    ports:
      - "1433:1433"
      - "22:22"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./backups:/host-backups
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Testing@1122 -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  backup-container:
    build: 
      dockerfile: Dockerfile
    container_name: backup-container
    volumes:
      - ./backup.sh:/backup.sh
      - mssql-data:/backups
      - ./backups:/host-backups
    command: /bin/sh -c "chmod +x /backup.sh && (crontab -l ; echo '*/2 * * * * /backup.sh >> /var/log/cron.log 2>&1') | crontab - && cron -f"
    links:
      - sqlserver
    depends_on:
      sqlserver:
          condition: service_healthy

volumes:
  mssql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /backups